export const ARTICLE_MUTATION_SET_ARTICLES = 'ARTICLE_MUTATION_SET_ARTICLES';
export const ARTICLE_ACTION_GET_ARTICLES = 'ARTICLE_ACTION_GET_ARTICLES';

export const AUTO_ACTION_LOGIN = 'AUTO_ACTION_LOGIN';
