export const ARTICLE_MUTATION_SET_ARTICLES = 'ARTICLE_MUTATION_SET_ARTICLES';
export const ARTICLE_ACTION_GET_ARTICLES = 'ARTICLE_ACTION_GET_ARTICLES';

export const ARTICLE_MUTATION_SET_ARTICLE = 'ARTICLE_MUTATION_SET_ARTICLE';
export const ARTICLE_ACTION_GET_ARTICLE = 'ARTICLE_ACTION_GET_ARTICLE';

export const ARTICLE_MUTATION_SET_ARTICLES_COUNTER =
  'ARTICLE_MUTATION_SET_ARTICLES_COUNTER';
export const ARTICLE_ACTION_GET_ARTICLE_COUNTER =
  'ARTICLE_ACTION_GET_ARTICLE_COUNTER';
export const ARTICLE_ACTION_PLUS_ARTICLE_COUNTER =
  'ARTICLE_ACTION_PLUS_ARTICLE_COUNTER';

export const TAG_MUTATION_SET_TAGS = 'TAG_MUTATION_SET_TAGS';
export const TAG_ACTION_GET_TAGS = 'TAG_ACTION_GET_TAGS';

export const CATEGORY_MUTATION_SET_CATEGORIES =
  'CATEGORY_MUTATION_SET_CATEGORIES';
export const CATEGORY_ACTION_GET_CATEGORIES = 'CATEGORY_ACTION_GET_CATEGORIES';

export const EVALUATION_MUTATION_APPEND_EVALUATIONS =
  'EVALUATION_MUTATION_APPEND_EVALUATIONS';

export const EVALUATION_ACTION_GET_EVALUATIONS =
  'EVALUATION_ACTION_GET_EVALUATIONS';

export const EVALUATION_ACTION_PUBLISH_EVALUATIONS =
  'EVALUATION_ACTION_PUBLISH_EVALUATIONS';

export const EVALUATION_MUTATION_CLEAR_EVALUATIONS =
  'EVALUATION_MUTATION_CLEAR_EVALUATIONS';
